// Seed data: a grocery catalog (with editable estimated prices) and budget-friendly dinners.
// Prices are rough US averages — edit them in Settings → Prices to match your store.

// Each item: name, aisle, unit the recipes use, pack size in that unit, price per pack.
export const CATALOG = {
  chicken_thigh:   { name: 'Chicken thighs, boneless', aisle: 'Meat & Seafood', unit: 'lb',  pack: 1.5, price: 5.49, freezer: true },
  chicken_breast:  { name: 'Chicken breast',           aisle: 'Meat & Seafood', unit: 'lb',  pack: 1.5, price: 6.99, freezer: true },
  ground_beef:     { name: 'Ground beef 80/20',        aisle: 'Meat & Seafood', unit: 'lb',  pack: 1,   price: 5.29, freezer: true },
  ground_turkey:   { name: 'Ground turkey',            aisle: 'Meat & Seafood', unit: 'lb',  pack: 1,   price: 4.99, freezer: true },
  pork_sausage:    { name: 'Smoked sausage',           aisle: 'Meat & Seafood', unit: 'oz',  pack: 14,  price: 4.29 },
  salmon:          { name: 'Salmon fillets (frozen)',  aisle: 'Frozen',         unit: 'lb',  pack: 1,   price: 8.99, freezer: true },
  shrimp:          { name: 'Shrimp, peeled (frozen)',  aisle: 'Frozen',         unit: 'lb',  pack: 1,   price: 7.99, freezer: true },
  eggs:            { name: 'Eggs',                     aisle: 'Dairy & Eggs',   unit: 'each',pack: 12,  price: 3.49 },
  milk:            { name: 'Milk',                     aisle: 'Dairy & Eggs',   unit: 'cup', pack: 8,   price: 2.19 },
  butter:          { name: 'Butter',                   aisle: 'Dairy & Eggs',   unit: 'tbsp',pack: 32,  price: 4.49 },
  cheddar:         { name: 'Shredded cheddar',         aisle: 'Dairy & Eggs',   unit: 'cup', pack: 2,   price: 2.99 },
  mozzarella:      { name: 'Shredded mozzarella',      aisle: 'Dairy & Eggs',   unit: 'cup', pack: 2,   price: 2.99 },
  parmesan:        { name: 'Grated parmesan',          aisle: 'Dairy & Eggs',   unit: 'cup', pack: 1.5, price: 3.99 },
  heavy_cream:     { name: 'Heavy cream',              aisle: 'Dairy & Eggs',   unit: 'cup', pack: 2,   price: 3.99 },
  sour_cream:      { name: 'Sour cream',               aisle: 'Dairy & Eggs',   unit: 'cup', pack: 2,   price: 2.29 },
  greek_yogurt:    { name: 'Plain Greek yogurt',       aisle: 'Dairy & Eggs',   unit: 'cup', pack: 4,   price: 4.49 },
  tofu:            { name: 'Firm tofu',                aisle: 'Produce',        unit: 'oz',  pack: 14,  price: 2.29 },
  onion:           { name: 'Yellow onion',             aisle: 'Produce',        unit: 'each',pack: 1,   price: 0.89 },
  garlic:          { name: 'Garlic (head)',            aisle: 'Produce',        unit: 'clove',pack: 10, price: 0.69 },
  bell_pepper:     { name: 'Bell pepper',              aisle: 'Produce',        unit: 'each',pack: 1,   price: 1.19 },
  carrot:          { name: 'Carrots',                  aisle: 'Produce',        unit: 'each',pack: 10,  price: 1.49 },
  celery:          { name: 'Celery',                   aisle: 'Produce',        unit: 'stalk',pack: 8,  price: 1.99 },
  potato:          { name: 'Russet potatoes',          aisle: 'Produce',        unit: 'each',pack: 8,   price: 4.49 },
  sweet_potato:    { name: 'Sweet potato',             aisle: 'Produce',        unit: 'each',pack: 1,   price: 1.09 },
  broccoli:        { name: 'Broccoli crown',           aisle: 'Produce',        unit: 'cup', pack: 4,   price: 1.99 },
  spinach:         { name: 'Baby spinach',             aisle: 'Produce',        unit: 'cup', pack: 5,   price: 2.99 },
  zucchini:        { name: 'Zucchini',                 aisle: 'Produce',        unit: 'each',pack: 1,   price: 0.99 },
  tomato:          { name: 'Roma tomato',              aisle: 'Produce',        unit: 'each',pack: 1,   price: 0.49 },
  lime:            { name: 'Lime',                     aisle: 'Produce',        unit: 'each',pack: 1,   price: 0.39 },
  lemon:           { name: 'Lemon',                    aisle: 'Produce',        unit: 'each',pack: 1,   price: 0.69 },
  cilantro:        { name: 'Cilantro',                 aisle: 'Produce',        unit: 'bunch',pack: 1,  price: 0.99 },
  green_onion:     { name: 'Green onions',             aisle: 'Produce',        unit: 'bunch',pack: 1,  price: 0.99 },
  ginger:          { name: 'Fresh ginger',             aisle: 'Produce',        unit: 'tbsp',pack: 6,   price: 0.99 },
  cabbage:         { name: 'Coleslaw mix',             aisle: 'Produce',        unit: 'cup', pack: 7,   price: 2.49 },
  avocado:         { name: 'Avocado',                  aisle: 'Produce',        unit: 'each',pack: 1,   price: 1.29 },
  rice:            { name: 'Long-grain white rice',    aisle: 'Pantry',         unit: 'cup', pack: 10,  price: 3.29 },
  pasta:           { name: 'Pasta (penne/spaghetti)',  aisle: 'Pantry',         unit: 'oz',  pack: 16,  price: 1.49 },
  egg_noodles:     { name: 'Egg noodles',              aisle: 'Pantry',         unit: 'oz',  pack: 12,  price: 2.29 },
  ramen:           { name: 'Ramen noodles',            aisle: 'Pantry',         unit: 'each',pack: 6,   price: 2.49 },
  tortillas:       { name: 'Flour tortillas (8")',     aisle: 'Bakery',         unit: 'each',pack: 10,  price: 2.99 },
  bread:           { name: 'Sandwich bread',           aisle: 'Bakery',         unit: 'slice',pack: 20, price: 2.79 },
  buns:            { name: 'Hamburger buns',           aisle: 'Bakery',         unit: 'each',pack: 8,   price: 2.49 },
  black_beans:     { name: 'Black beans (can)',        aisle: 'Pantry',         unit: 'can', pack: 1,   price: 0.99 },
  chickpeas:       { name: 'Chickpeas (can)',          aisle: 'Pantry',         unit: 'can', pack: 1,   price: 0.99 },
  kidney_beans:    { name: 'Kidney beans (can)',       aisle: 'Pantry',         unit: 'can', pack: 1,   price: 0.99 },
  lentils:         { name: 'Dry lentils',              aisle: 'Pantry',         unit: 'cup', pack: 2.5, price: 1.79 },
  diced_tomato:    { name: 'Diced tomatoes (can)',     aisle: 'Pantry',         unit: 'can', pack: 1,   price: 1.09 },
  crushed_tomato:  { name: 'Crushed tomatoes (28oz)',  aisle: 'Pantry',         unit: 'can', pack: 1,   price: 1.99 },
  marinara:        { name: 'Marinara sauce',           aisle: 'Pantry',         unit: 'cup', pack: 3,   price: 2.49 },
  coconut_milk:    { name: 'Coconut milk (can)',       aisle: 'Pantry',         unit: 'can', pack: 1,   price: 1.89 },
  chicken_broth:   { name: 'Chicken broth',            aisle: 'Pantry',         unit: 'cup', pack: 4,   price: 2.29 },
  salsa:           { name: 'Salsa',                    aisle: 'Pantry',         unit: 'cup', pack: 2,   price: 2.79 },
  corn:            { name: 'Frozen corn',              aisle: 'Frozen',         unit: 'cup', pack: 4,   price: 1.49 },
  peas:            { name: 'Frozen peas',              aisle: 'Frozen',         unit: 'cup', pack: 4,   price: 1.49 },
  stir_fry_veg:    { name: 'Frozen stir-fry veggies',  aisle: 'Frozen',         unit: 'cup', pack: 5,   price: 2.49 },
  peanut_butter:   { name: 'Peanut butter',            aisle: 'Pantry',         unit: 'tbsp',pack: 32,  price: 2.99, staple: true },
  soy_sauce:       { name: 'Soy sauce',                aisle: 'Pantry',         unit: 'tbsp',pack: 20,  price: 2.49, staple: true },
  honey:           { name: 'Honey',                    aisle: 'Pantry',         unit: 'tbsp',pack: 24,  price: 4.99, staple: true },
  olive_oil:       { name: 'Olive oil',                aisle: 'Pantry',         unit: 'tbsp',pack: 34,  price: 6.99, staple: true },
  flour:           { name: 'All-purpose flour',        aisle: 'Pantry',         unit: 'cup', pack: 18,  price: 3.49, staple: true },
  curry_powder:    { name: 'Curry powder',             aisle: 'Spices',         unit: 'tsp', pack: 20,  price: 2.99, staple: true },
  chili_powder:    { name: 'Chili powder',             aisle: 'Spices',         unit: 'tsp', pack: 25,  price: 1.99, staple: true },
  cumin:           { name: 'Ground cumin',             aisle: 'Spices',         unit: 'tsp', pack: 20,  price: 1.99, staple: true },
  italian_season:  { name: 'Italian seasoning',        aisle: 'Spices',         unit: 'tsp', pack: 25,  price: 1.99, staple: true },
  paprika:         { name: 'Smoked paprika',           aisle: 'Spices',         unit: 'tsp', pack: 20,  price: 2.49, staple: true },
  taco_season:     { name: 'Taco seasoning packet',    aisle: 'Spices',         unit: 'each',pack: 1,   price: 0.79 },
  sriracha:        { name: 'Sriracha',                 aisle: 'Pantry',         unit: 'tbsp',pack: 28,  price: 3.49, staple: true },
  oats:            { name: 'Rolled oats',              aisle: 'Pantry',         unit: 'cup', pack: 15,  price: 4.29 },
  granola:         { name: 'Granola',                  aisle: 'Pantry',         unit: 'cup', pack: 3.5, price: 3.99 },
  syrup:           { name: 'Pancake syrup',            aisle: 'Pantry',         unit: 'tbsp',pack: 24,  price: 2.99 },
  cinnamon:        { name: 'Ground cinnamon',          aisle: 'Spices',         unit: 'tsp', pack: 24,  price: 1.99, staple: true },
  tuna:            { name: 'Tuna (can)',               aisle: 'Pantry',         unit: 'can', pack: 1,   price: 1.19 },
  tomato_soup:     { name: 'Tomato soup (can)',        aisle: 'Pantry',         unit: 'can', pack: 1,   price: 1.29 },
  mayo:            { name: 'Mayonnaise',               aisle: 'Pantry',         unit: 'tbsp',pack: 30,  price: 3.79 },
  caesar:          { name: 'Caesar dressing',          aisle: 'Pantry',         unit: 'tbsp',pack: 16,  price: 2.99 },
  hummus:          { name: 'Hummus',                   aisle: 'Produce',        unit: 'tbsp',pack: 16,  price: 3.49 },
  banana:          { name: 'Banana',                   aisle: 'Produce',        unit: 'each',pack: 1,   price: 0.27 },
  apple:           { name: 'Apple',                    aisle: 'Produce',        unit: 'each',pack: 1,   price: 0.89 },
  cucumber:        { name: 'Cucumber',                 aisle: 'Produce',        unit: 'each',pack: 1,   price: 0.79 },
  romaine:         { name: 'Romaine hearts (3-pack)',  aisle: 'Produce',        unit: 'cup', pack: 9,   price: 3.49 },
  deli_turkey:     { name: 'Sliced deli turkey',       aisle: 'Meat & Seafood', unit: 'oz',  pack: 9,   price: 4.49 },
  cheese_slices:   { name: 'Sliced cheese',            aisle: 'Dairy & Eggs',   unit: 'slice',pack: 12, price: 2.99 },
  english_muffins: { name: 'English muffins',          aisle: 'Bakery',         unit: 'each',pack: 6,   price: 2.29 },
  frozen_berries:  { name: 'Frozen mixed berries',     aisle: 'Frozen',         unit: 'cup', pack: 3,   price: 3.49 },
};

export const AISLE_ORDER = ['Produce', 'Meat & Seafood', 'Dairy & Eggs', 'Bakery', 'Frozen', 'Pantry', 'Spices', 'Other'];

// Recipes are written for `serves` people; everything scales from there.
// Macros are per serving (approximate). `meals` says which meals a recipe can fill (default: dinner).
export const RECIPES = [
  {
    id: 'sheet-pan-chicken-fajitas', name: 'Sheet-Pan Chicken Fajitas', emoji: '🌮', serves: 4, minutes: 30,
    tags: ['mexican', 'sheet-pan'], macros: { cal: 520, protein: 36, carbs: 48, fat: 20 },
    ingredients: [['chicken_thigh', 1.5], ['bell_pepper', 3], ['onion', 1], ['tortillas', 8], ['taco_season', 1], ['lime', 1], ['sour_cream', 0.5], ['olive_oil', 2]],
    steps: ['Heat oven to 425°F.', 'Slice chicken, peppers and onion into strips.', 'Toss everything with oil and taco seasoning on a sheet pan.', 'Roast 20–22 min, until chicken is cooked through.', 'Squeeze lime over, warm tortillas, and serve with sour cream.'],
  },
  {
    id: 'beef-tacos', name: 'Weeknight Beef Tacos', emoji: '🌮', serves: 4, minutes: 20,
    tags: ['mexican', 'kid-friendly'], macros: { cal: 560, protein: 30, carbs: 40, fat: 30 },
    ingredients: [['ground_beef', 1], ['taco_season', 1], ['tortillas', 8], ['cheddar', 1], ['tomato', 2], ['cabbage', 2], ['salsa', 0.5]],
    steps: ['Brown beef in a skillet, 6–8 min; drain fat.', 'Stir in taco seasoning and ⅔ cup water; simmer 5 min.', 'Dice tomatoes.', 'Fill warm tortillas with beef, cheese, slaw, tomato and salsa.'],
  },
  {
    id: 'black-bean-quesadillas', meals: ['dinner', 'lunch'], name: 'Black Bean & Corn Quesadillas', emoji: '🫓', serves: 4, minutes: 20,
    tags: ['vegetarian', 'mexican', 'kid-friendly'], macros: { cal: 480, protein: 20, carbs: 58, fat: 18 },
    ingredients: [['black_beans', 2], ['corn', 1], ['cheddar', 2], ['tortillas', 8], ['salsa', 1], ['cumin', 1]],
    steps: ['Rinse beans; mash half of them with cumin.', 'Spread mashed beans on 4 tortillas; top with whole beans, corn and cheese.', 'Top with remaining tortillas.', 'Cook in a dry skillet 3 min per side until crisp.', 'Cut in wedges; serve with salsa.'],
  },
  {
    id: 'spaghetti-meat-sauce', name: 'Spaghetti with Meat Sauce', emoji: '🍝', serves: 4, minutes: 30,
    tags: ['italian', 'kid-friendly'], macros: { cal: 640, protein: 32, carbs: 78, fat: 20 },
    ingredients: [['pasta', 16], ['ground_beef', 1], ['marinara', 3], ['onion', 1], ['garlic', 3], ['parmesan', 0.25]],
    steps: ['Boil pasta in salted water per package.', 'Meanwhile brown beef with diced onion and garlic, 8 min.', 'Add marinara; simmer 10 min.', 'Toss with drained pasta; top with parmesan.'],
  },
  {
    id: 'turkey-chili', meals: ['dinner', 'lunch'], name: 'One-Pot Turkey Chili', emoji: '🥣', serves: 6, minutes: 40,
    tags: ['soup', 'freezer-friendly'], macros: { cal: 380, protein: 30, carbs: 38, fat: 11 },
    ingredients: [['ground_turkey', 1], ['kidney_beans', 2], ['black_beans', 1], ['crushed_tomato', 1], ['onion', 1], ['bell_pepper', 1], ['garlic', 3], ['chili_powder', 3], ['cumin', 2], ['cheddar', 0.5]],
    steps: ['Brown turkey with diced onion, pepper and garlic, 8 min.', 'Stir in chili powder and cumin; cook 1 min.', 'Add rinsed beans and crushed tomatoes plus 1 cup water.', 'Simmer 25 min, stirring now and then.', 'Top with cheddar. Leftovers freeze well.'],
  },
  {
    id: 'chicken-fried-rice', name: 'Chicken Fried Rice', emoji: '🍚', serves: 4, minutes: 25,
    tags: ['asian', 'kid-friendly'], macros: { cal: 510, protein: 30, carbs: 62, fat: 14 },
    ingredients: [['rice', 1.5], ['chicken_breast', 1], ['eggs', 3], ['peas', 1], ['carrot', 2], ['green_onion', 1], ['soy_sauce', 3], ['garlic', 2]],
    steps: ['Cook rice (best made earlier and chilled).', 'Dice chicken and stir-fry in a hot oiled pan until cooked; set aside.', 'Cook diced carrots, peas and garlic 3 min.', 'Push aside, scramble eggs, then add rice, chicken and soy sauce.', 'Fry 3–4 min; finish with sliced green onions.'],
  },
  {
    id: 'honey-garlic-salmon', name: 'Honey Garlic Salmon & Rice', emoji: '🐟', serves: 4, minutes: 25,
    tags: ['seafood', 'high-protein'], macros: { cal: 560, protein: 34, carbs: 58, fat: 20 },
    ingredients: [['salmon', 1.25], ['honey', 3], ['soy_sauce', 2], ['garlic', 3], ['rice', 1.5], ['broccoli', 3]],
    steps: ['Start rice.', 'Whisk honey, soy sauce and minced garlic.', 'Sear salmon skin-side up 4 min, flip, add sauce and cook 3–4 min more.', 'Steam broccoli 5 min.', 'Serve salmon over rice with broccoli; spoon sauce over.'],
  },
  {
    id: 'lentil-curry', meals: ['dinner', 'lunch'], name: 'Coconut Lentil Curry', emoji: '🍛', serves: 4, minutes: 35,
    tags: ['vegetarian', 'vegan', 'freezer-friendly'], macros: { cal: 470, protein: 18, carbs: 64, fat: 16 },
    ingredients: [['lentils', 1], ['coconut_milk', 1], ['diced_tomato', 1], ['onion', 1], ['garlic', 3], ['ginger', 1], ['curry_powder', 3], ['spinach', 2], ['rice', 1.5]],
    steps: ['Start rice.', 'Sauté diced onion, garlic and ginger 5 min.', 'Add curry powder; cook 1 min.', 'Add rinsed lentils, tomatoes, coconut milk and 2 cups water; simmer 20–25 min.', 'Stir in spinach until wilted. Serve over rice.'],
  },
  {
    id: 'chickpea-tikka', meals: ['dinner', 'lunch'], name: 'Chickpea Tikka Masala', emoji: '🍛', serves: 4, minutes: 30,
    tags: ['vegetarian'], macros: { cal: 490, protein: 16, carbs: 70, fat: 16 },
    ingredients: [['chickpeas', 2], ['crushed_tomato', 1], ['greek_yogurt', 0.5], ['onion', 1], ['garlic', 3], ['ginger', 1], ['curry_powder', 3], ['rice', 1.5], ['cilantro', 1]],
    steps: ['Start rice.', 'Sauté onion, garlic and ginger 5 min.', 'Add curry powder, then crushed tomatoes and rinsed chickpeas; simmer 15 min.', 'Off heat, stir in yogurt.', 'Top with cilantro; serve over rice.'],
  },
  {
    id: 'shrimp-stir-fry', name: 'Garlic Shrimp Stir-Fry', emoji: '🍤', serves: 4, minutes: 20,
    tags: ['asian', 'seafood', 'high-protein'], macros: { cal: 430, protein: 30, carbs: 56, fat: 8 },
    ingredients: [['shrimp', 1], ['stir_fry_veg', 4], ['soy_sauce', 3], ['honey', 1], ['garlic', 4], ['ginger', 1], ['rice', 1.5]],
    steps: ['Start rice.', 'Stir-fry frozen veggies in a hot oiled pan 5 min.', 'Add garlic, ginger and thawed shrimp; cook 3 min until pink.', 'Stir in soy sauce and honey; toss 1 min.', 'Serve over rice.'],
  },
  {
    id: 'peanut-noodles', meals: ['dinner', 'lunch'], name: 'Spicy Peanut Noodles with Tofu', emoji: '🍜', serves: 4, minutes: 25,
    tags: ['asian', 'vegetarian', 'vegan'], macros: { cal: 540, protein: 22, carbs: 60, fat: 24 },
    ingredients: [['ramen', 4], ['tofu', 14], ['peanut_butter', 4], ['soy_sauce', 3], ['sriracha', 1], ['lime', 1], ['cabbage', 2], ['green_onion', 1]],
    steps: ['Press and cube tofu; pan-fry until golden, 8 min.', 'Cook noodles (discard seasoning packets); save ½ cup water.', 'Whisk peanut butter, soy, sriracha, lime juice and noodle water.', 'Toss noodles, sauce, slaw and tofu.', 'Top with green onions.'],
  },
  {
    id: 'sausage-potato-bake', name: 'Sausage, Potato & Pepper Bake', emoji: '🥔', serves: 4, minutes: 40,
    tags: ['sheet-pan', 'kid-friendly'], macros: { cal: 540, protein: 18, carbs: 44, fat: 32 },
    ingredients: [['pork_sausage', 14], ['potato', 4], ['bell_pepper', 2], ['onion', 1], ['olive_oil', 2], ['paprika', 2]],
    steps: ['Heat oven to 425°F.', 'Cube potatoes; slice sausage, peppers and onion.', 'Toss with oil, paprika, salt and pepper on a sheet pan.', 'Roast potatoes 15 min alone, then add the rest and roast 20 min more.'],
  },
  {
    id: 'baked-ziti', name: 'Cheesy Baked Ziti', emoji: '🧀', serves: 6, minutes: 45,
    tags: ['italian', 'vegetarian', 'kid-friendly'], macros: { cal: 520, protein: 22, carbs: 68, fat: 17 },
    ingredients: [['pasta', 16], ['marinara', 3], ['mozzarella', 2], ['parmesan', 0.5], ['spinach', 2], ['garlic', 2], ['italian_season', 2]],
    steps: ['Heat oven to 375°F. Boil pasta 2 min less than package says.', 'Mix pasta, marinara, spinach, garlic, seasoning and half the mozzarella.', 'Pour into a baking dish; top with remaining mozzarella and parmesan.', 'Bake 20 min until bubbly.'],
  },
  {
    id: 'chicken-noodle-soup', meals: ['dinner', 'lunch'], name: 'Chicken Noodle Soup', emoji: '🍲', serves: 6, minutes: 40,
    tags: ['soup', 'kid-friendly'], macros: { cal: 330, protein: 28, carbs: 30, fat: 10 },
    ingredients: [['chicken_thigh', 1.5], ['egg_noodles', 8], ['carrot', 3], ['celery', 3], ['onion', 1], ['garlic', 2], ['chicken_broth', 8], ['italian_season', 1]],
    steps: ['Sauté diced onion, carrot, celery and garlic 6 min.', 'Add broth, seasoning and whole chicken thighs; simmer 20 min.', 'Remove chicken, shred it, and return to pot.', 'Add noodles; cook 6–8 min until tender.'],
  },
  {
    id: 'smash-burgers', name: 'Smash Burgers & Oven Fries', emoji: '🍔', serves: 4, minutes: 35,
    tags: ['kid-friendly'], macros: { cal: 720, protein: 32, carbs: 62, fat: 38 },
    ingredients: [['ground_beef', 1], ['buns', 4], ['cheddar', 0.5], ['onion', 1], ['tomato', 1], ['potato', 3], ['olive_oil', 2]],
    steps: ['Heat oven to 450°F. Cut potatoes into wedges, toss with oil and salt; roast 30 min.', 'Divide beef into 8 balls.', 'Smash onto a very hot skillet; cook 2 min, flip, add cheese, cook 1 min.', 'Stack two patties per bun with onion and tomato.'],
  },
  {
    id: 'veggie-frittata', name: 'Spinach & Potato Frittata', emoji: '🍳', serves: 4, minutes: 30,
    tags: ['vegetarian', 'high-protein'], macros: { cal: 360, protein: 22, carbs: 20, fat: 21 },
    ingredients: [['eggs', 10], ['potato', 2], ['spinach', 3], ['onion', 1], ['cheddar', 0.75], ['milk', 0.5], ['bread', 4]],
    steps: ['Heat oven to 400°F.', 'Dice potatoes and onion; cook in an oven-safe skillet 10 min.', 'Add spinach until wilted.', 'Whisk eggs, milk and cheese; pour over veggies.', 'Cook on stove 3 min, then bake 12–15 min until set. Serve with toast.'],
  },
  {
    id: 'turkey-sweet-potato-bowls', name: 'Turkey Sweet Potato Bowls', emoji: '🍠', serves: 4, minutes: 35,
    tags: ['high-protein'], macros: { cal: 470, protein: 30, carbs: 50, fat: 15 },
    ingredients: [['ground_turkey', 1], ['sweet_potato', 3], ['black_beans', 1], ['avocado', 1], ['salsa', 0.5], ['chili_powder', 2], ['olive_oil', 1]],
    steps: ['Heat oven to 425°F. Cube sweet potatoes, toss with oil; roast 25 min.', 'Brown turkey with chili powder, 8 min.', 'Warm rinsed beans.', 'Build bowls with sweet potato, turkey and beans; top with avocado and salsa.'],
  },
  {
    id: 'lemon-chicken-orzo', name: 'Lemon Chicken Pasta', emoji: '🍋', serves: 4, minutes: 30,
    tags: ['italian', 'high-protein'], macros: { cal: 580, protein: 38, carbs: 62, fat: 18 },
    ingredients: [['chicken_breast', 1.5], ['pasta', 12], ['lemon', 2], ['garlic', 3], ['spinach', 2], ['parmesan', 0.5], ['butter', 2], ['chicken_broth', 1]],
    steps: ['Boil pasta.', 'Cube chicken; brown in butter 6–7 min.', 'Add garlic, broth and juice of both lemons; simmer 3 min.', 'Toss in pasta and spinach until wilted.', 'Finish with parmesan and lemon zest.'],
  },
  {
    id: 'bbq-chicken-sliders', name: 'Slow-Cooker BBQ-Style Pulled Chicken', emoji: '🥪', serves: 6, minutes: 20,
    tags: ['slow-cooker', 'kid-friendly', 'freezer-friendly'], macros: { cal: 440, protein: 32, carbs: 46, fat: 13 },
    ingredients: [['chicken_thigh', 2], ['crushed_tomato', 1], ['honey', 4], ['paprika', 2], ['onion', 1], ['buns', 6], ['cabbage', 3]],
    steps: ['Add chicken, crushed tomatoes, honey, paprika and diced onion to a slow cooker.', 'Cook on low 6 hours (or high 3).', 'Shred chicken in the sauce.', 'Serve on buns topped with slaw.'],
  },
  {
    id: 'minestrone', meals: ['dinner', 'lunch'], name: 'Hearty Minestrone', emoji: '🥣', serves: 6, minutes: 40,
    tags: ['soup', 'vegetarian', 'vegan', 'freezer-friendly'], macros: { cal: 310, protein: 12, carbs: 54, fat: 5 },
    ingredients: [['pasta', 6], ['kidney_beans', 1], ['diced_tomato', 2], ['zucchini', 1], ['carrot', 2], ['celery', 2], ['onion', 1], ['garlic', 3], ['spinach', 2], ['italian_season', 2]],
    steps: ['Sauté onion, carrot, celery and garlic 6 min.', 'Add tomatoes, seasoning and 6 cups water; simmer 15 min.', 'Add diced zucchini, beans and pasta; cook 10 min.', 'Stir in spinach. Season well with salt and pepper.'],
  },
  {
    id: 'egg-fried-rice-veg', meals: ['dinner', 'lunch'], name: 'Veggie Egg Fried Rice', emoji: '🍳', serves: 4, minutes: 20,
    tags: ['asian', 'vegetarian'], macros: { cal: 420, protein: 15, carbs: 64, fat: 12 },
    ingredients: [['rice', 1.5], ['eggs', 5], ['stir_fry_veg', 3], ['soy_sauce', 3], ['green_onion', 1], ['garlic', 2], ['sriracha', 1]],
    steps: ['Cook rice (day-old is best).', 'Stir-fry veggies and garlic 4 min.', 'Push aside, scramble eggs.', 'Add rice and soy sauce; fry 3–4 min.', 'Top with green onion and sriracha.'],
  },
  {
    id: 'loaded-baked-potatoes', name: 'Loaded Baked Potatoes', emoji: '🥔', serves: 4, minutes: 60,
    tags: ['kid-friendly', 'vegetarian'], macros: { cal: 500, protein: 18, carbs: 66, fat: 19 },
    ingredients: [['potato', 4], ['broccoli', 3], ['cheddar', 1], ['sour_cream', 0.5], ['green_onion', 1], ['butter', 2]],
    steps: ['Heat oven to 425°F. Prick potatoes, rub with oil and salt.', 'Bake 50–60 min until tender.', 'Steam broccoli 5 min.', 'Split potatoes, fluff with butter, top with broccoli, cheese, sour cream and green onion.'],
  },
  {
    id: 'shrimp-tacos', name: 'Chili-Lime Shrimp Tacos', emoji: '🦐', serves: 4, minutes: 20,
    tags: ['mexican', 'seafood'], macros: { cal: 440, protein: 28, carbs: 46, fat: 15 },
    ingredients: [['shrimp', 1], ['tortillas', 8], ['cabbage', 2], ['lime', 2], ['avocado', 1], ['chili_powder', 2], ['sour_cream', 0.5], ['cilantro', 1]],
    steps: ['Toss thawed shrimp with chili powder and salt.', 'Sear in a hot pan 2 min per side; squeeze over 1 lime.', 'Mix sour cream with juice of the other lime.', 'Fill tortillas with slaw, shrimp, avocado, cilantro and lime crema.'],
  },
  {
    id: 'stuffed-peppers', name: 'Beef & Rice Stuffed Peppers', emoji: '🫑', serves: 4, minutes: 50,
    tags: ['high-protein'], macros: { cal: 520, protein: 28, carbs: 40, fat: 26 },
    ingredients: [['bell_pepper', 4], ['ground_beef', 1], ['rice', 0.75], ['diced_tomato', 1], ['mozzarella', 1], ['onion', 1], ['italian_season', 2]],
    steps: ['Heat oven to 375°F. Cook rice.', 'Brown beef and onion; stir in tomatoes, seasoning and rice.', 'Halve and seed peppers; fill with mixture.', 'Top with mozzarella; cover with foil and bake 25 min, uncovered 5 more.'],
  },
  // ---------- Breakfasts ----------
  {
    id: 'overnight-oats', name: 'Berry Overnight Oats', emoji: '🥣', serves: 4, minutes: 5, meals: ['breakfast'],
    tags: ['vegetarian', 'make-ahead'], macros: { cal: 340, protein: 15, carbs: 54, fat: 7 },
    ingredients: [['oats', 2], ['milk', 2], ['greek_yogurt', 1], ['frozen_berries', 2], ['honey', 2]],
    steps: ['Stir oats, milk, yogurt and honey together.', 'Divide into 4 jars and top with frozen berries.', 'Refrigerate overnight (keeps 4 days). Eat cold or warm 1 min.'],
  },
  {
    id: 'eggs-toast', name: 'Scrambled Eggs & Toast', emoji: '🍳', serves: 2, minutes: 10, meals: ['breakfast'],
    tags: ['vegetarian', 'high-protein', 'kid-friendly'], macros: { cal: 380, protein: 20, carbs: 28, fat: 20 },
    ingredients: [['eggs', 5], ['bread', 4], ['butter', 2], ['milk', 0.25]],
    steps: ['Whisk eggs with milk and a pinch of salt.', 'Melt butter in a pan over medium-low heat.', 'Cook eggs, stirring gently, until just set, 3–4 min.', 'Serve with buttered toast.'],
  },
  {
    id: 'breakfast-burritos', name: 'Freezer Breakfast Burritos', emoji: '🌯', serves: 6, minutes: 30, meals: ['breakfast'],
    tags: ['vegetarian', 'make-ahead', 'freezer-friendly'], macros: { cal: 420, protein: 19, carbs: 44, fat: 18 },
    ingredients: [['eggs', 8], ['tortillas', 6], ['black_beans', 1], ['cheddar', 1], ['potato', 2], ['salsa', 0.5]],
    steps: ['Dice potatoes small; pan-fry in oil until crisp, 12 min.', 'Scramble eggs.', 'Warm tortillas; fill with eggs, potatoes, rinsed beans, cheese and salsa.', 'Roll up. Eat now, or wrap in foil and freeze (reheat 2 min in microwave).'],
  },
  {
    id: 'banana-pancakes', name: 'Banana Pancakes', emoji: '🥞', serves: 4, minutes: 20, meals: ['breakfast'],
    tags: ['vegetarian', 'kid-friendly'], macros: { cal: 410, protein: 11, carbs: 66, fat: 11 },
    ingredients: [['flour', 1.5], ['eggs', 2], ['milk', 1.25], ['banana', 2], ['butter', 3], ['syrup', 6]],
    steps: ['Mash bananas; whisk in eggs, milk and 2 tbsp melted butter.', 'Stir in flour, 1 tbsp sugar, 2 tsp baking powder and a pinch of salt until just combined.', 'Cook ¼-cup scoops on a buttered pan, 2 min per side.', 'Serve with syrup.'],
  },
  {
    id: 'yogurt-parfait', name: 'Yogurt Granola Parfait', emoji: '🍓', serves: 2, minutes: 5, meals: ['breakfast'],
    tags: ['vegetarian', 'quick'], macros: { cal: 360, protein: 20, carbs: 48, fat: 9 },
    ingredients: [['greek_yogurt', 1.5], ['granola', 0.75], ['frozen_berries', 1], ['honey', 1]],
    steps: ['Thaw berries a few minutes (or overnight in the fridge).', 'Layer yogurt, berries and granola in bowls.', 'Drizzle with honey.'],
  },
  {
    id: 'pb-banana-toast', name: 'Peanut Butter Banana Toast', emoji: '🍌', serves: 2, minutes: 5, meals: ['breakfast'],
    tags: ['vegetarian', 'vegan', 'quick', 'kid-friendly'], macros: { cal: 390, protein: 13, carbs: 50, fat: 17 },
    ingredients: [['bread', 4], ['peanut_butter', 4], ['banana', 2], ['cinnamon', 0.5]],
    steps: ['Toast bread.', 'Spread with peanut butter.', 'Top with sliced banana and a sprinkle of cinnamon.'],
  },
  {
    id: 'egg-muffins', name: 'Veggie Egg Muffin Cups', emoji: '🧁', serves: 4, minutes: 25, meals: ['breakfast'],
    tags: ['vegetarian', 'high-protein', 'make-ahead'], macros: { cal: 230, protein: 17, carbs: 5, fat: 15 },
    ingredients: [['eggs', 10], ['spinach', 1], ['bell_pepper', 1], ['cheddar', 0.5], ['onion', 0.5]],
    steps: ['Heat oven to 350°F and grease a 12-cup muffin tin.', 'Divide chopped spinach, pepper and onion among the cups.', 'Whisk eggs with salt and pepper; pour over veggies and top with cheese.', 'Bake 20 min. Keeps 4 days in the fridge.'],
  },
  {
    id: 'apple-cinnamon-oatmeal', name: 'Apple Cinnamon Oatmeal', emoji: '🍎', serves: 2, minutes: 10, meals: ['breakfast'],
    tags: ['vegetarian', 'quick'], macros: { cal: 320, protein: 10, carbs: 58, fat: 6 },
    ingredients: [['oats', 1], ['milk', 2], ['apple', 1], ['cinnamon', 1], ['honey', 1]],
    steps: ['Bring milk to a simmer.', 'Stir in oats, diced apple and cinnamon.', 'Cook 5 min, stirring, until thick.', 'Sweeten with honey.'],
  },
  {
    id: 'egg-muffin-sandwich', name: 'Egg & Cheese Muffin Sandwiches', emoji: '🥯', serves: 2, minutes: 10, meals: ['breakfast'],
    tags: ['vegetarian', 'high-protein', 'kid-friendly'], macros: { cal: 360, protein: 19, carbs: 28, fat: 18 },
    ingredients: [['english_muffins', 2], ['eggs', 2], ['cheese_slices', 2], ['butter', 1]],
    steps: ['Toast English muffins.', 'Fry eggs in butter; break yolks and flip after 2 min.', 'Top each egg with cheese to melt.', 'Sandwich in muffins.'],
  },

  // ---------- Lunches ----------
  {
    id: 'turkey-sandwich', name: 'Turkey & Cheese Sandwiches', emoji: '🥪', serves: 2, minutes: 5, meals: ['lunch'],
    tags: ['quick', 'kid-friendly'], macros: { cal: 430, protein: 26, carbs: 36, fat: 19 },
    ingredients: [['bread', 4], ['deli_turkey', 4], ['cheese_slices', 2], ['romaine', 1], ['tomato', 1], ['mayo', 2], ['apple', 2]],
    steps: ['Spread bread with mayo.', 'Layer turkey, cheese, lettuce and sliced tomato.', 'Serve with an apple on the side.'],
  },
  {
    id: 'tuna-salad', name: 'Tuna Salad Sandwiches', emoji: '🐟', serves: 2, minutes: 10, meals: ['lunch'],
    tags: ['quick', 'high-protein'], macros: { cal: 420, protein: 28, carbs: 30, fat: 20 },
    ingredients: [['tuna', 2], ['mayo', 3], ['celery', 1], ['bread', 4], ['romaine', 1], ['lemon', 0.5]],
    steps: ['Drain tuna; mix with mayo, finely diced celery, a squeeze of lemon, salt and pepper.', 'Spread on bread with lettuce.'],
  },
  {
    id: 'chicken-caesar-wraps', name: 'Chicken Caesar Wraps', emoji: '🌯', serves: 4, minutes: 20, meals: ['lunch'],
    tags: ['high-protein', 'make-ahead'], macros: { cal: 480, protein: 34, carbs: 34, fat: 22 },
    ingredients: [['chicken_breast', 1], ['tortillas', 4], ['romaine', 4], ['parmesan', 0.25], ['caesar', 6]],
    steps: ['Season chicken with salt and pepper; pan-cook 6 min per side, then slice.', 'Toss chopped romaine with dressing and parmesan.', 'Fill tortillas with salad and chicken; roll tightly. Keeps 2 days wrapped.'],
  },
  {
    id: 'grilled-cheese-soup', name: 'Grilled Cheese & Tomato Soup', emoji: '🧀', serves: 2, minutes: 15, meals: ['lunch'],
    tags: ['vegetarian', 'kid-friendly'], macros: { cal: 520, protein: 18, carbs: 52, fat: 26 },
    ingredients: [['bread', 4], ['cheese_slices', 4], ['butter', 2], ['tomato_soup', 1]],
    steps: ['Heat soup with a can of water (or milk).', 'Butter the outside of the bread; fill with cheese.', 'Cook in a pan over medium heat, 3 min per side, until golden.'],
  },
  {
    id: 'hummus-wraps', name: 'Hummus Veggie Wraps', emoji: '🥙', serves: 2, minutes: 10, meals: ['lunch'],
    tags: ['vegetarian', 'vegan', 'quick'], macros: { cal: 390, protein: 12, carbs: 52, fat: 15 },
    ingredients: [['tortillas', 2], ['hummus', 6], ['cucumber', 1], ['carrot', 1], ['spinach', 1], ['bell_pepper', 0.5]],
    steps: ['Spread hummus over tortillas.', 'Add spinach, sliced cucumber, shredded carrot and pepper strips.', 'Roll up tightly and cut in half.'],
  },
  {
    id: 'chickpea-salad', name: 'Greek Chickpea Salad', emoji: '🥗', serves: 4, minutes: 15, meals: ['lunch'],
    tags: ['vegetarian', 'vegan', 'make-ahead'], macros: { cal: 330, protein: 11, carbs: 38, fat: 15 },
    ingredients: [['chickpeas', 2], ['cucumber', 1], ['tomato', 3], ['onion', 0.5], ['lemon', 1], ['olive_oil', 3], ['italian_season', 1]],
    steps: ['Rinse chickpeas; dice cucumber, tomatoes and onion.', 'Whisk lemon juice, olive oil, seasoning, salt and pepper.', 'Toss everything together. Keeps 3 days in the fridge.'],
  },
  {
    id: 'bean-cheese-burritos', name: 'Bean, Rice & Cheese Burritos', emoji: '🌯', serves: 4, minutes: 25, meals: ['lunch'],
    tags: ['vegetarian', 'make-ahead', 'freezer-friendly'], macros: { cal: 510, protein: 19, carbs: 72, fat: 15 },
    ingredients: [['tortillas', 4], ['black_beans', 1], ['rice', 0.75], ['cheddar', 1], ['salsa', 0.5], ['cumin', 1]],
    steps: ['Cook rice.', 'Warm beans with cumin and mash lightly.', 'Fill tortillas with rice, beans, cheese and salsa; roll up.', 'Toast seam-side down in a pan 2 min. Freeze extras in foil.'],
  },
  {
    id: 'pasta-salad', name: 'Italian Pasta Salad', emoji: '🍝', serves: 4, minutes: 20, meals: ['lunch'],
    tags: ['vegetarian', 'make-ahead'], macros: { cal: 440, protein: 14, carbs: 56, fat: 18 },
    ingredients: [['pasta', 8], ['bell_pepper', 1], ['cucumber', 1], ['tomato', 2], ['mozzarella', 0.75], ['olive_oil', 3], ['italian_season', 2]],
    steps: ['Cook pasta; rinse under cold water.', 'Dice pepper, cucumber and tomatoes.', 'Toss with mozzarella, olive oil, seasoning, salt and a splash of vinegar if you have it.', 'Chill. Keeps 4 days.'],
  },
];
